# Generated by Django 3.2.16 on 2023-11-11 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20231111_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Follow',
        ),
    ]
